---
abstract: 'Module to compare data with pattern'
author:
  - 'cono <cono@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132510'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-PatternCompare
resources:
  bugtracker: https://github.com/cono/p5-data-patterncompare/issues
  homepage: https://github.com/cono/p5-data-patterncompare
  repository: https://github.com/cono/p5-data-pattern-compare.git
version: v0.01
